services:
  telegraf:
    image: fabianbees/docker-telegraf-smartmontools:latest
    group_add:
      - "$DOCKER_GROUP"
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /run/udev:/run/udev:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: --config $INFLUX_CONFIG
    environment:
      - HOST_MOUNT_PREFIX=/rootfs
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
      - HOST_ETC=/rootfs/etc
      - INFLUX_TOKEN=$INFLUX_TOKEN

