version: '2.2'

services:

  # External dependencies
  redis:
    image: redis:alpine
    restart: $RESTART_POLICY
    volumes:
      - "${DATA_DIR}/redis:/data"
    sysctls:
      - vm.overcommit_memory=1
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  database:
    image: mariadb:11
    restart: $RESTART_POLICY
    environment:
      MARIADB_ROOT_PASSWORD: mailu-root
      MARIADB_DATABASE: mailu
      MARIADB_USER: mailu
      MARIADB_PASSWORD: mailu
    volumes:
      - "${DATA_DIR}/mariadb:/var/lib/mysql"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  backup:
    image: tiredofit/db-backup
    restart: $RESTART_POLICY
    volumes:
      - "${DATA_DIR}/db-backup:/backup"
    environment:
      - TIMEZONE=UTC
      - DB_TYPE=mariadb
      - DB_HOST=database
      - DB_USER=root
      - DB_PASS=mailu
      - DB_NAME=mailu
      - COMPRESSION=NONE
      - ENABLE_CHECKSUM=FALSE
      - CHECKSUM=SHA1
      - DB_DUMP_BEGIN=0315
      - DB_DUMP_FREQ=1440
      - DB_CLEANUP_TIME=10080
      - CREATE_LATEST_SYMLINK=TRUE
    depends_on:
      - resolver
      - database
    dns:
      - 192.168.203.254
    labels:
      - "backup.enable=true"
      - "backup.password=$RESTIC_PASSWORD"
      - "backup.volumes=${DATA_DIR}/db-backup"

  certdumper:
    restart: $RESTART_POLICY
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}traefik-certdumper:${MAILU_VERSION}
    environment:
      - DOMAIN=$HOSTNAMES
      # Set TRAEFIK_VERSION to v2 in your .env if you're using Traefik v2
      - TRAEFIK_VERSION=${TRAEFIK_VERSION:-v2}
    volumes:
      - "${TRAEFIK_ACME_DIR}:/traefik"
      - "${DATA_DIR}/certs:/output"

  # Core services
  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION}
    restart: $RESTART_POLICY 
    env_file: .env
    logging:
      driver: journald
      options:
        tag: mailu-front
    ports:
      - "$BIND_ADDRESS4:25:25"
      - "$BIND_ADDRESS6:25:25"
      - "$BIND_ADDRESS4:465:465"
      - "$BIND_ADDRESS6:465:465"
      - "$BIND_ADDRESS4:587:587"
      - "$BIND_ADDRESS6:587:587"
      - "$BIND_ADDRESS4:110:110"
      - "$BIND_ADDRESS6:110:110"
      - "$BIND_ADDRESS4:995:995"
      - "$BIND_ADDRESS6:995:995"
      - "$BIND_ADDRESS4:143:143"
      - "$BIND_ADDRESS6:143:143"
      - "$BIND_ADDRESS4:993:993"
      - "$BIND_ADDRESS6:993:993"
    networks:
      - default
      - webmail
      - radicale
      - traefik
    volumes:
      - "${DATA_DIR}/certs:/certs"
      - "${DATA_DIR}/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      # Mailu Service
      - "traefik.http.services.mailu-svc.loadbalancer.server.port=80"
      # Web UI
      - "traefik.http.routers.mailu.rule=Host(`$HOSTNAMES`)"
      - "traefik.http.routers.mailu.entrypoints=websecure"
      - "traefik.http.routers.mailu.tls=true"
      - "traefik.http.routers.mailu.tls.domains[0].main=$HOSTNAMES"
      - "traefik.http.routers.mailu.tls.domains[0].sans=$ADDITIONAL_SANS"
      - "traefik.http.routers.mailu.service=mailu-svc"
      # Autoconfig
      - "traefik.http.routers.mailu-autoconfig.rule=HostRegexp(`{host:(autodiscover|autoconfig).+}`)"
      - "traefik.http.routers.mailu-autoconfig.entrypoints=web"
      - "traefik.http.routers.mailu-autoconfig.priority=100"
      - "traefik.http.routers.mailu-autoconfig.service=mailu-svc"


  resolver:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION}
    env_file: .env
    restart: $RESTART_POLICY 
    networks:
      default:
        ipv4_address: 192.168.203.254

  admin:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION}
    restart: $RESTART_POLICY
    env_file: .env
    logging:
      driver: journald
      options:
        tag: mailu-admin
    volumes:
      - "${DATA_DIR}/data:/data"
      - "${DATA_DIR}/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 192.168.203.254

  imap:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION}
    restart: $RESTART_POLICY
    env_file: .env
    logging:
      driver: journald
      options:
        tag: mailu-imap
    volumes:
      - "${DATA_DIR}/mail:/mail"
      - "${DATA_DIR}/overrides/dovecot:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  smtp:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION}
    restart: $RESTART_POLICY
    env_file: .env
    logging:
      driver: journald
      options:
        tag: mailu-smtp
    volumes:
      - "${DATA_DIR}/mailqueue:/queue"
      - "${DATA_DIR}/overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  oletools:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}oletools:${MAILU_VERSION}
    hostname: oletools
    restart: $RESTART_POLICY
    networks:
      - noinet
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  antispam:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION}
    hostname: antispam
    restart: $RESTART_POLICY
    env_file: .env
    logging:
      driver: journald
      options:
        tag: mailu-antispam
    networks:
      - default
      - noinet
    volumes:
      - "${DATA_DIR}/filter:/var/lib/rspamd"
      - "${DATA_DIR}/overrides/rspamd:/overrides:ro"
    depends_on:
      - front
      - redis
      - oletools
      - resolver
    dns:
      - 192.168.203.254

  # Optional services

  webdav:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}radicale:${MAILU_VERSION}
    restart: $RESTART_POLICY
    volumes:
      - "${DATA_DIR}/dav:/data"
    networks:
      - radicale

  fetchmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION}
    restart: $RESTART_POLICY
    env_file: .env
    volumes:
      - "${DATA_DIR}/data/fetchmail:/data"
    depends_on:
      - admin
      - smtp
      - imap
      - resolver
    dns:
      - 192.168.203.254

  # Webmail
  webmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION}
    restart: $RESTART_POLICY
    env_file: .env
    volumes:
      - "${DATA_DIR}/webmail:/data"
      - "${DATA_DIR}/overrides/snappymail:/overrides:ro"
    networks:
      - webmail
    depends_on:
      - front

networks:
  default:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
        - subnet: fd90:6937:741e:beef::/64
  radicale:
    driver: bridge
  webmail:
    driver: bridge
  noinet:
    driver: bridge
    internal: true

  traefik:
    external: true
