
# Configuration file version (not SDNS version)
version = "1.5.0"

# ============================
# Basic Server Configuration
# ============================

# Working directory for SDNS database and cache files
# This directory must have write permissions for the SDNS user
directory = "db"

# DNS server bind address and port
bind = ":53"

# DNS-over-TLS (DoT) server bind address and port
# Requires TLS certificate and key to be configured
# bindtls = ":853"

# DNS-over-HTTPS (DoH) server bind address and port
# Requires TLS certificate and key to be configured
# binddoh = ":443"

# DNS-over-QUIC (DoQ) server bind address and port
# Requires TLS certificate and key to be configured
# binddoq = ":853"

# TLS certificate file path (PEM format)
# Required for DoT, DoH, and DoQ servers
# tlscertificate = "server.crt"

# TLS private key file path (PEM format)
# Required for DoT, DoH, and DoQ servers
# tlsprivatekey = "server.key"

# ============================
# Network Configuration
# ============================

# Outbound IPv4 addresses for DNS queries
# Multiple addresses enable random source IP selection per request
outboundips = [
]

# Outbound IPv6 addresses for DNS queries
# Multiple addresses enable random source IP selection per request
outboundip6s = [
]

# ============================
# Root DNS Servers
# ============================

# Root DNS servers (IPv4)
# These are the authoritative name servers for the DNS root zone
rootservers = [
    "198.41.0.4:53",      # a.root-servers.net
    "199.9.14.201:53",    # b.root-servers.net
    "192.33.4.12:53",     # c.root-servers.net
    "199.7.91.13:53",     # d.root-servers.net
    "192.203.230.10:53",  # e.root-servers.net
    "192.5.5.241:53",     # f.root-servers.net
    "192.112.36.4:53",    # g.root-servers.net
    "198.97.190.53:53",   # h.root-servers.net
    "192.36.148.17:53",   # i.root-servers.net
    "192.58.128.30:53",   # j.root-servers.net
    "193.0.14.129:53",    # k.root-servers.net
    "199.7.83.42:53",     # l.root-servers.net
    "202.12.27.33:53"     # m.root-servers.net
]

# Root DNS servers (IPv6)
# These are the authoritative name servers for the DNS root zone
root6servers = [
    "[2001:503:ba3e::2:30]:53",  # a.root-servers.net
    "[2001:500:200::b]:53",      # b.root-servers.net
    "[2001:500:2::c]:53",        # c.root-servers.net
    "[2001:500:2d::d]:53",       # d.root-servers.net
    "[2001:500:a8::e]:53",       # e.root-servers.net
    "[2001:500:2f::f]:53",       # f.root-servers.net
    "[2001:500:12::d0d]:53",     # g.root-servers.net
    "[2001:500:1::53]:53",       # h.root-servers.net
    "[2001:7fe::53]:53",         # i.root-servers.net
    "[2001:503:c27::2:30]:53",   # j.root-servers.net
    "[2001:7fd::1]:53",          # k.root-servers.net
    "[2001:500:9f::42]:53",      # l.root-servers.net
    "[2001:dc3::35]:53"          # m.root-servers.net
]

# ============================
# DNSSEC Configuration
# ============================

# DNSSEC validation mode
# "on" = validate DNSSEC for signed zones
# "off" = disable DNSSEC validation
dnssec = "on"

# DNSSEC root trust anchors
# These are the public keys used to verify the DNS root zone
rootkeys = [
	# Key ID 20326 - Active since 2017
	"""\
	. 172800 IN DNSKEY 257 3 8 ( \
	AwEAAaz/tAm8yTn4Mfeh5eyI96WSVexTBAvkMgJzkKTO \
	iW1vkIbzxeF3+/4RgWOq7HrxRixHlFlExOLAJr5emLvN \
	7SWXgnLh4+B5xQlNVz8Og8kvArMtNROxVQuCaSnIDdD5 \
	LKyWbRd2n9WGe2R8PzgCmr3EgVLrjyBxWezF0jLHwVN8 \
	efS3rCj/EWgvIWgb9tarpVUDK/b58Da+sqqls3eNbuv7 \
	pr+eoZG+SrDK6nWeL3c6H5Apxz7LjVc1uTIdsIXxuOLY \
	A4/ilBmSVIzuDWfdRUfhHdY6+cn8HFRm+2hM8AnXGXws \
	9555KrUB5qihylGa8subX2Nn6UwNR1AkUTV74bU= \
	) ; KSK; alg = RSASHA256 ; key id = 20326 \
	""",
	# Key ID 38696 - Active since 2024
	"""\
	. 172800 IN DNSKEY 257 3 8 ( \
	AwEAAa96jeuknZlaeSrvyAJj6ZHv28hhOKkx3rLGXVaC \
	6rXTsDc449/cidltpkyGwCJNnOAlFNKF2jBosZBU5eeH \
	spaQWOmOElZsjICMQMC3aeHbGiShvZsx4wMYSjH8e7Vr \
	hbu6irwCzVBApESjbUdpWWmEnhathWu1jo+siFUiRAAx \
	m9qyJNg/wOZqqzL/dL/q8PkcRU5oUKEpUge71M3ej2/7 \
	CPqpdVwuMoTvoB+ZOT4YeGyxMvHmbrxlFzGOHOijtzN+ \
	u1TQNatX2XBuzZNQ1K+s2CXkPIZo7s6JgZyvaBevYtxP \
	vYLw4z9mR7K2vaF18UYH9Z9GNUUeayffKC73PYc= \
	) ; KSK; alg = RSASHA256 ; key id = 38696 \
	"""
]

# ============================
# Upstream Servers
# ============================

# Fallback DNS servers
# Used when root servers are unreachable or for specific failures
# Supports standard DNS (port 53)
fallbackservers = [
    # Examples:
    # "8.8.8.8:53",              # Google Public DNS
    # "[2001:4860:4860::8888]:53" # Google Public DNS IPv6
]

# Forwarder DNS servers
# When configured, SDNS acts as a forwarding resolver instead of recursive
# Supports DNS (port 53) and DNS-over-TLS (tls:// prefix)
forwarderservers = [
    # Examples:
    # "8.8.8.8:53",              # Standard DNS
    # "[2001:4860:4860::8888]:53", # Standard DNS IPv6
    # "tls://8.8.8.8:853"        # DNS-over-TLS
]

# ============================
# API and Logging
# ============================

# HTTP API server configuration
# Provides REST API for statistics and management
# Set to empty string to disable
api = "127.0.0.1:8080"

# API authentication token
# When set, requests must include: Authorization: Bearer <token>
# bearertoken = ""

# Log verbosity level
# Options: crit, error, warn, info, debug
loglevel = "info"

# Query access log file path
# Uses Common Log Format (CLF)
# Leave empty to disable access logging
# accesslog = ""

# ============================
# Filtering and Blocking
# ============================

# Remote blocklist sources
# These URLs are periodically downloaded and updated
blocklists = [
    # Popular blocklist examples:
    # "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts",
    # "http://sysctl.org/cameleon/hosts",
    # "https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt",
    # "https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt"
]

# [DEPRECATED] Blocklist directory - automatically created under working directory
blocklistdir = ""

# Response IP for blocked A queries (IPv4)
nullroute = "0.0.0.0"

# Response IP for blocked AAAA queries (IPv6)
nullroutev6 = "::0"

# ============================
# Access Control
# ============================

# Client access control list (ACL)
# CIDR notation for allowed client IP ranges
accesslist = [
    "0.0.0.0/0",    # Allow all IPv4
    "::0/0"         # Allow all IPv6
]

# Local hosts file path
# Serves entries from hosts file (RFC 952/1123 format)
# Leave empty to disable
hostsfile = ""

# ============================
# Performance and Limits
# ============================

# Network timeout for upstream DNS queries
timeout = "2s"

# Maximum time to wait for any DNS query to complete
querytimeout = "10s"

# Cache TTL for error responses (seconds)
expire = 600

# Maximum number of cached DNS records
cachesize = 256000

# Prefetch threshold percentage (10-90)
# Refreshes popular cache entries before expiration
# Set to 0 to disable prefetching
prefetch = 10

# Maximum recursion depth for queries
# Prevents infinite loops in resolution
maxdepth = 30

# ============================
# Rate Limiting
# ============================

# Global query rate limit (queries per second)
# 0 = disabled
ratelimit = 0

# Per-client rate limit (queries per minute)
# 0 = disabled
clientratelimit = 0

# ============================
# Domain Metrics
# ============================

# Enable per-domain query metrics
# Tracks query counts for individual domains
domainmetrics = false

# Maximum number of domains to track in metrics
# 0 = unlimited (use with caution - may consume memory)
# Recommended: 10000-100000 for production
domainmetricslimit = 10000

# ============================
# Custom Lists
# ============================

# Manual domain blocklist
# Domains listed here will be blocked
blocklist = [
    # Examples:
    # "ads.example.com",
    # "tracker.example.net"
]

# Domain whitelist
# Domains listed here bypass all blocking
whitelist = [
    # Examples:
    # "important.example.com",
    # "trusted.example.net"
]

# ============================
# Advanced Features
# ============================

# DNS server identifier (RFC 5001)
# Useful for identifying specific servers in multi-server deployments
# Leave empty to disable
nsid = ""

# CHAOS query responses
# Responds to: version.bind, version.server, hostname.bind, id.server
chaos = true

# QNAME minimization level (RFC 7816)
# Higher values increase privacy but may impact performance
# 0 = disabled, 5 = recommended
qname_min_level = 5

# Empty zones (AS112 - RFC 7534)
# Prevents queries for private IP reverse zones from leaking
# Default list used if empty
emptyzones = [
    # Example: "10.in-addr.arpa."
]

# ============================
# TCP Connection Pooling
# ============================

# Enable TCP connection pooling for root and TLD servers
# Keeps TCP connections alive to improve performance
tcpkeepalive = false

# TCP idle timeout for root server connections
# Connections idle longer than this are closed
roottcptimeout = "5s"

# TCP idle timeout for TLD server connections (com, net, org, etc.)
# Connections idle longer than this are closed
tldtcptimeout = "10s"

# Maximum number of pooled TCP connections
# 0 = use default (100)
tcpmaxconnections = 100

# ============================
# Dnstap Binary Logging
# ============================

# Dnstap socket path
# Unix domain socket for binary DNS logging
# Leave empty to disable
# dnstapsocket = "/var/run/sdns/dnstap.sock"

# Dnstap server identity
# Identifies this server in dnstap logs
# dnstapidentity = "sdns"

# Dnstap version string
# Version identifier for dnstap logs
# dnstapversion = "1.0"

# Log DNS queries via dnstap
# dnstaplogqueries = true

# Log DNS responses via dnstap
# dnstaplogresponses = true

# Dnstap buffer flush interval (seconds)
# dnstapflushinterval = 5

# ============================
# Plugins
# ============================

# External plugin configuration
# Plugins extend SDNS functionality
# Load order affects processing sequence
# Example: https://github.com/semihalev/sdnsexampleplugin

# [plugins]
#     [plugins.example]
#     path = "exampleplugin.so"
#     config = {key_1 = "value_1", key_2 = 2, key_3 = true}
