version: '3.2'

services:
    changedetection:
      image: ghcr.io/dgtlmoon/changedetection.io
      container_name: changedetection
      hostname: changedetection
      volumes:
        - $CONTAINER_DIR:/datastore
      environment:
        - PUID=1000
        - PGID=1000
        - LOGGER_LEVEL=INFO
        - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000
        - BASE_URL=https://${VIRTUAL_HOST}
        - HIDE_REFERER=true
        - FETCH_WORKERS=3
      restart: unless-stopped
      networks:
        - default
        - traefik
      depends_on:
        playwright-chrome:
          condition: service_started
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.routers.changedetection.entrypoints=websecure"
        - "traefik.http.routers.changedetection.rule=HOST(`$VIRTUAL_HOST`)"
        - "traefik.http.routers.changedetection.service=changedetection-srv"
        - "traefik.http.services.changedetection-srv.loadbalancer.server.port=5000"
        - "traefik.http.services.changedetection-srv.loadbalancer.server.scheme=http"
      logging:
        driver: "json-file"
        options:
          max-size: "512k"
          max-file: "1"


    playwright-chrome:
      hostname: playwright-chrome
      image: dgtlmoon/sockpuppetbrowser:latest
      cap_add:
        - SYS_ADMIN
      restart: unless-stopped
      environment:
        - SCREEN_WIDTH=1920
        - SCREEN_HEIGHT=1024
        - SCREEN_DEPTH=16
        - MAX_CONCURRENT_CHROME_PROCESSES=3
      logging:
        driver: "json-file"
        options:
          max-size: "256k"
          max-file: "1"


networks:
  traefik:
    external: true
