version: "3"

services:
  teamspeak:
    image: teamspeak:3.13
    restart: unless-stopped
    networks: [ts]
    ports:
      - "9987:9987/udp"
      - "9999:9999/udp"
      - "30033:30033"
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: db
      TS3SERVER_DB_PORT: 3306
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: $DB_ROOT_PASSWORD
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_QUERY_PROTOCOLS: ssh
      TS3SERVER_LICENSE: accept
    volumes:
      - ${CONTAINER_DIR}/teamspeak:/var/ts3server
    labels:
      - "backup.enable=true"
      - "backup.password=$RESTIC_PASSWORD"
      - "backup.volumes=${CONTAINER_DIR}/teamspeak"
      - "backup.exclude=*/files/*,*/logs/*"

  db:
    image: mariadb:10.9
    restart: unless-stopped
    networks: [ts]
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: teamspeak
    volumes:
      - ${CONTAINER_DIR}/db:/var/lib/mysql


  backup:
    image: tiredofit/db-backup
    depends_on:
      - db
    volumes:
      - ${CONTAINER_DIR}/db-backup:/backup
    environment:
      - TIMEZONE=UTC
      - DB_TYPE=mariadb
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=$DB_ROOT_PASSWORD
      - DB_NAME=teamspeak
      - COMPRESSION=NONE
      - ENABLE_CHECKSUM=FALSE
      - CHECKSUM=SHA1
      - DB_DUMP_BEGIN=0315
      - DB_DUMP_FREQ=1440
      - DB_CLEANUP_TIME=10080
      - CREATE_LATEST_SYMLINK=TRUE
    restart: unless-stopped
    networks: [ts]
    labels:
      - "backup.enable=true"
      - "backup.password=$RESTIC_PASSWORD"
      - "backup.volumes=${CONTAINER_DIR}/db-backup"

networks:
  ts:
