version: '3'

services:

  app:
    image: jauderho/tailscale:latest
    volumes:
      - ./data/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    logging:
      driver: json-file
      options:
        max-size: 50m
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.forwarding=1
    command: tailscaled
    restart: unless-stopped
    networks:
      vpn:
        ipv4_address: 10.100.101.2
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  vpn:
    external: true
