version: "3.8"

services:
  app:
    image: jauderho/tailscale:latest
    command: tailscaled
    restart: unless-stopped
    networks:
      vpn:
        ipv4_address: 10.100.101.2
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.forwarding=1
    volumes:
      - ${CONTAINER_DIR}/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"

networks:
  vpn:
    external: true
