services:
  influx:
    image: influxdb:alpine
    restart: unless-stopped
    ports:
      - "8086:8086"
    networks: [traefik]
    volumes:
      - ${CONTAINER_DIR}/influx/data:/var/lib/influxdb2
      - ${CONTAINER_DIR}/influx/config:/etc/influxdb2
    environment:
      - PUID=1000
      - PGID=1000
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=$INFLUXDB_INIT_USERNAME
      - DOCKER_INFLUXDB_INIT_PASSWORD=$INFLUXDB_INIT_PASSWORD
      - DOCKER_INFLUXDB_INIT_ORG=$INFLUXDB_INIT_ORG
      - DOCKER_INFLUXDB_INIT_BUCKET=default
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.influx.entrypoints=websecure"
      - "traefik.http.routers.influx.rule=Host(`$VIRTUAL_HOST_INFLUX`)"
      - "traefik.http.routers.influx.service=influx-srv"
      - "traefik.http.services.influx-srv.loadbalancer.server.port=8086"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  mqtt:
    image: emqx/emqx:5.7
    restart: unless-stopped
    #ports:
      # TCP
      #- "1883:1883"
      # Websocket
      #- "8083:8083"
      # Secure Websocket
      #- "8084:8084"
      # SSL
      #- "8883:8883"
    networks: [traefik]
    environment:
      - EMQX_HOST=emqx-docker
    volumes:
      #- ${CONTAINER_DIR}/mqtt/etc:/opt/emqx/etc
      - ${CONTAINER_DIR}/mqtt/data:/opt/emqx/data
      - ${CONTAINER_DIR}/mqtt/log:/opt/emqx/log
      - ./emqx.conf:/opt/emqx/etc/emqx.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.mqtt-ui.entrypoints=web"
      - "traefik.http.routers.mqtt-ui.rule=Host(`$VIRTUAL_HOST_EMQX`)"
      - "traefik.http.routers.mqtt-ui.priority=100"
      - "traefik.http.services.mqtt-ui.loadbalancer.server.port=18083"
      - "traefik.http.routers.mqtt-ui.service=mqtt-ui"

      - "traefik.http.routers.mqtt-ws.entrypoints=websecure"
      - "traefik.http.routers.mqtt-ws.rule=Host(`$VIRTUAL_HOST_EMQX_WS`) && PathPrefix(`/mqtt`)"
      - "traefik.http.services.mqtt-ws.loadbalancer.server.port=8083"
      - "traefik.http.routers.mqtt-ws.service=mqtt-ws"

      - "traefik.tcp.routers.mqtt-notls.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mqtt-notls.entrypoints=mqtt"
      - "traefik.tcp.routers.mqtt-notls.service=mqtt-notls"
      - "traefik.tcp.routers.mqtt-notls.tls=false"
      - "traefik.tcp.services.mqtt-notls.loadbalancer.server.port=1883"
      - "traefik.tcp.services.mqtt-notls.loadbalancer.proxyprotocol.version=2"

      - "traefik.tcp.routers.mqtt-tls.rule=HostSNI(`$VIRTUAL_HOST_EMQX_WS`)"
      - "traefik.tcp.routers.mqtt-tls.entrypoints=mqtt-tls"
      - "traefik.tcp.routers.mqtt-tls.service=mqtt-tls"
      - "traefik.tcp.routers.mqtt-tls.tls=true"
      - "traefik.tcp.services.mqtt-tls.loadbalancer.server.port=1883"
      - "traefik.tcp.services.mqtt-tls.loadbalancer.proxyprotocol.version=2"

      - "diun.enable=true"

      - "telegraf.enabled=true"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  traefik:
    external: true
