version: "3.8"

services:
  client:
    image: tailscale/tailscale:latest
    command: tailscaled
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ${CONTAINER_DIR}/tailscale:/var/lib
      - /dev/net/tun:/dev/net/tun
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"
