services:

  pmsr:
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - TZ=Europe/Berlin
      - PLEX_CLAIM=$CLAIM_TOKEN
      - ADVERTISE_IP=http://$ADVERTISE_IP:32400/
    volumes:
      - "$PLEX_LIBRARY:/config"
      - "$TRANSCODING_TMP:/transcode"
      - "$MOVIE_DIR:/mnt/video/Filme"
      - "$SERIES_DIR:/mnt/video/Serien"
      - "$MUSIC_DIR:/mnt/music"
    devices:
      - /dev/dri:/dev/dri
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"

