services:
  vaultwarden:
    image: ghcr.io/dani-garcia/vaultwarden:latest
    restart: unless-stopped
    networks: [traefik, default]
    depends_on: [db]
    volumes:
      - ${CONTAINER_DIR}/vaultwarden:/data
    environment:
      - DATABASE_URL=mysql://vaultwarden:vaultwarden@db/vaultwarden
      - WEBSOCKET_ENABLED=true
      - RUST_BACKTRACE=1
      - REQUIRE_DEVICE_EMAIL=true
      - SIGNUPS_ALLOWED=$SIGNUPS_ALLOWED
      - SIGNUPS_VERIFY=$SIGNUPS_VERIFY
      - SIGNUPS_DOMAINS_WHITELIST=$SIGNUPS_DOMAINS_WHITELIST
      - ADMIN_TOKEN=$ADMIN_TOKEN
      - DISABLE_ADMIN_TOKEN=$DISABLE_ADMIN_TOKEN
      - INVITATIONS_ALLOWED=$INVITATIONS_ALLOWED
      - INVITATION_ORG_NAME=$INVITATION_ORG_NAME
      - DOMAIN=$DOMAIN
      - SMTP_HOST=$SMTP_HOST
      - SMTP_FROM=$SMTP_FROM
      - SMTP_FROM_NAME=$SMTP_FROM_NAME
      - SMTP_PORT=$SMTP_PORT
      - SMTP_SECURITY=$SMTP_SECURITY
      - SMTP_USERNAME=$SMTP_USERNAME
      - SMTP_PASSWORD=$SMTP_PASSWORD
      - PUSH_ENABLED=$PUSH_ENABLED
      - PUSH_INSTALLATION_ID=$PUSH_INSTALLATION_ID
      - PUSH_INSTALLATION_KEY=$PUSH_INSTALLATION_KEY
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.vaultwarden.rule=Host(`${VIRTUAL_HOST}`)"
      - "traefik.http.routers.vaultwarden.service=vaultwarden"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  db:
    image: mariadb:10.9
    restart: unless-stopped
    volumes:
      - ${CONTAINER_DIR}/db:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=vaultwarden
      - MARIADB_DATABASE=vaultwarden
      - MARIADB_PASSWORD=vaultwarden
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"

networks:
  traefik:
    external: true

