services:

  zipline:
    image: ghcr.io/diced/zipline:v4
    restart: $RESTART_POLICY
    networks: [default, traefik]
    depends_on: [postgres]
    volumes:
      - "${CONTAINER_DIR}/zipline/uploads:/zipline/uploads"
      - "${CONTAINER_DIR}/zipline/public:/zipline/public"
    environment:
      - CORE_SECRET=$SECRET_KEY
      - CORE_HOSTNAME=0.0.0.0
      - CORE_PORT=3000
      - DATABASE_URL=postgres://postgres:postgres@postgres/zipline_v4_new
      - DATASOURCE_TYPE=local
      - DATASOURCE_LOCAL_DIRECTORY=/zipline/uploads
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.zipline.entrypoints=websecure"
      - "traefik.http.routers.zipline.rule=Host(`$VIRTUAL_HOST`)"
      - "traefik.http.routers.zipline.service=zipline-srv"
      - "traefik.http.services.zipline-srv.loadbalancer.server.port=3000"

      - "backup.enable=true"
      - "backup.password=$RESTIC_PASSWORD"
      - "backup.volumes=${CONTAINER_DIR}/zipline/uploads,${CONTAINER_DIR}_DIR}/zipline/public"

      - "diun.enable=true"

      - "telegraf.enabled=true"

  postgres:
    image: postgres:15
    restart: $RESTART_POLICY
    volumes:
      - "${CONTAINER_DIR}/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    healthcheck:
      test: pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      interval: 10s
      timeout: 5s
      retries: 5

  backup:
    image: tiredofit/db-backup:4.0.19
    restart: $RESTART_POLICY
    depends_on: [postgres]
    volumes:
      - "${CONTAINER_DIR}/db-backup:/backup"
    environment:
      - TIMEZONE=UTC
      - CONTAINER_ENABLE_MONITORING=FALSE
      - DEFAULT_LOG_LEVEL=WARN

      - DEFAULT_CREATE_LATEST_SYMLINK=TRUE
      - BACKUP_JOB_CONCURRENCY=1
      - DEFAULT_CHECKSUM=NONE
      - DEFAULT_COMPRESSION=NONE
      - DEFAULT_BACKUP_INTERVAL=1440
      - DEFAULT_BACKUP_BEGIN=0315
      - DEFAULT_CLEANUP_TIME=10080

      - DB01_TYPE=postgres
      - DB01_HOST=postgres
      - DB01_NAME=postgres
      - DB01_USER=postgres
      - DB01_PASS=postgres
    labels:
      - "backup.enable=true"
      - "backup.password=$RESTIC_PASSWORD"
      - "backup.volumes=${CONTAINER_DIR}/db-backup"

networks:
  traefik:
    external: true
