version: "3"

services:
  server:
    image: gitea/gitea:1.20
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
      - traefik
    volumes:
      - ./data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "222:22"
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.gitea.entrypoints=websecure"
      - "traefik.http.routers.gitea.rule=HOST(`$VIRTUAL_HOST`)"
      - "traefik.http.routers.gitea.service=gitea-srv"
      - "traefik.http.services.gitea-srv.loadbalancer.server.port=3000"
      - "backup.enable=true"
      - "backup.password=$RESTIC_PASSWORD"
      - "backup.volumes=./data/gitea"

  db:
    image: mariadb:10.9
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks: [gitea]
    volumes:
      - ./data/db:/var/lib/mysql

  backup:
    image: tiredofit/db-backup
    depends_on:
      - db
    volumes:
      - ./data/db-backup:/backup
    environment:
      - TIMEZONE=UTC
      - DB_TYPE=mariadb
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=gitea
      - DB_NAME=gitea
      - COMPRESSION=NONE
      - ENABLE_CHECKSUM=FALSE
      - CHECKSUM=SHA1
      - DB_DUMP_BEGIN=0315
      - DB_DUMP_FREQ=1440
      - DB_CLEANUP_TIME=10080
      - CREATE_LATEST_SYMLINK=TRUE
    restart: unless-stopped
    networks: [gitea]
    labels:
      - "backup.enable=true"
      - "backup.password=$RESTIC_PASSWORD"
      - "backup.volumes=./data/db-backup"

networks:
  gitea:
  traefik:
    external: true
