services:
  ntfy:
    image: binwiederhier/ntfy:latest
    restart: unless-stopped
    networks: [traefik]
    command: serve
    volumes:
      - "${CONTAINER_DIR}/ntfy:/var/lib/ntfy"
    environment:
      - NTFY_BASE_URL=https://${VIRTUAL_HOST}
      - NTFY_CACHE_FILE=/var/lib/ntfy/cache.db
      - NTFY_AUTH_FILE=/var/lib/ntfy/auth.db
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
      - NTFY_BEHIND_PROXY=true
      - NTFY_ATTACHMENT_CACHE_DIR=/var/lib/ntfy/attachments
      - NTFY_ENABLE_LOGIN=true
      - NTFY_LOG_LEVEL=INFO
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.ntfy.entrypoints=websecure"
      - "traefik.http.routers.ntfy.rule=HOST(`$VIRTUAL_HOST`)"
      - "traefik.http.routers.ntfy.service=ntfy-srv"
      - "traefik.http.services.ntfy-srv.loadbalancer.server.port=80"

      - "backup.enable=true"
      - "backup.password=$RESTIC_PASSWORD"
      - "backup.volumes=${CONTAINER_DIR}/ntfy"

      - "diun.enable=true"

      - "telegraf.enabled=true"
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"


networks:
  traefik:
    external: true
