version: "3.8"

services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    network_mode: host
    volumes:
      - "${CONTAINER_DIR}/homeassistant/config:/config"
      - "/etc/localtime:/etc/localtime:ro"
    logging:
      driver: "local"
      options:
        max-size: "2m"
        max-file: "1"
