version: "3.8"

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - "${CONTAINER_DIR}/homeassistant/config:/config"
      - "/etc/localtime:/etc/localtime:ro"
      - "/run/dbus:/run/dbus:ro"
    #devices:
    #  - "/dev/ttyUSB0:/dev/ttyUSB0"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.rule=Host(`$VIRTUAL_HOST`)"
      - "traefik.http.routers.homeassistant.entrypoints=websecure"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  matter-server:
    container_name: matter-server
    image: "ghcr.io/home-assistant-libs/python-matter-server:stable"
    restart: unless-stopped
    network_mode: host
    security_opt:
      - apparmor=unconfined
    volumes:
      - "${CONTAINER_DIR}/matter:/data"
      - "/run/dbus:/run/dbus:ro"
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"

  vscode:
    container_name: vscode
    image: "linuxserver/code-server:latest"
    restart: unless-stopped 
    ports:
      - "8888:8443"
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Berlin
      - PASSWORD=$VSCODE_PASSWORD
      - DEFAULT_WORKSPACE=/workspace
    volumes:
      - "${CONTAINER_DIR}/homeassistant/config:/workspace"
      - "${CONTAINER_DIR}/code:/config"
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"
