services:

  jmusicbot:
    image: ghcr.io/yojoshb/jmusicbot-docker
    environment:
      - BOT_VERSION=0.3.9
    volumes:
      - "$CONTAINER_DIR/config:/config"
    restart: unless-stopped
    labels:
      - "backup.enable=true"
      - "backup.password=$RESTIC_PASSWORD"
      - "backup.volumes=${CONTAINER_DIR}"
