services:
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: unless-stopped
    networks: [traefik]
    security_opt:
      - no-new-privileges:true
    ports:
      # HTTP
      - "0.0.0.0:80:80"
      - "[::]:80:80"
      # HTTPS 1.x-2.x
      - "0.0.0.0:443:443/tcp"
      - "[::]:443:443/tcp"
      # QUIC
      - "0.0.0.0:443:443/udp"
      - "[::]:443:443/udp"
      # traefik dashboard
      - "0.0.0.0:9999:9999"
      - "[::]:9999:9999"
      # MQTT TCP Router
      - "0.0.0.0:1883:1883"
      - "[::]:1883:1883"
      # MQTT TLS TCP Router
      - "0.0.0.0:8883:8883"
      - "[::]:8883:8883"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/traefik.yml:ro"
      - "./config:/etc/traefik/config:ro"
      - "${CONTAINER_DIR}/certificates:/var/certificates"
    environment:
      TRAEFIK_CERTIFICATESRESOLVERS_letsencrypt_ACME_EMAIL: $ACME_MAIL
    labels:
      # https://blog.creekorful.org/2020/01/how-to-expose-traefik-2-dashboard-securely-docker-swarm/
      - "traefik.enable=true"
      #- "traefik.http.services.traefik.loadbalancer.server.port=8080" # required by swarm but not used.
      - "traefik.http.routers.traefik.rule=PathPrefix(`/`)"
      - "traefik.http.routers.traefik.entrypoints=dashboard"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${DASHBOARD_USERNAME}:${DASHBOARD_PASSWORD}"

      - "diun.enable=true"

      - "telegraf.enabled=true"

    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  traefik:
    external: true
