log:
  level: INFO

accessLog: {}

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          priority: 10
          to: websecure
          scheme: https
          permanent: false
    transport:
      respondingTimeouts:
        readTimeout: "0s"
  websecure:
    address: ":443"
    http3: {}
    http:
      tls:
        certResolver: letsencrypt
    transport:
      respondingTimeouts:
        readTimeout: "0s"
  dashboard:
    address: ":9999"
  mqtt:
    address: ":1883"
  mqtt-tls:
    address: ":8883"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /etc/traefik/config/
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      #email: it@example.com
      storage: /var/certificates/acme.json
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      keyType: RSA4096
      httpChallenge:
        entryPoint: web

serversTransport:
  insecureSkipVerify: true

api:
  insecure: false
  dashboard: true
#  entryPoint: dashboard

metrics:
  prometheus: 
    entryPoint: dashboard
