version: "3"

services:

  fastbin-rewritten:
    image: reg.mc8051.de/jozsefsallai/fastbin-rewritten:latest
    restart: unless-stopped
    volumes:
      - ./data:/app/storage
    environment:
      - PORT=3000
      - NEXT_PUBLIC_SITE_URL=http://localhost:3000
      - STORAGE_STRATEGY=file
      - LIMITS_MAX_BODY_LENGTH=500000
      - LIMITS_MAX_PAYLOAD_SIZE=5mb
      - FILE_STORAGE_LOCATION=storage
      - SERVER_SECRET=$SERVER_SECRET
    networks: [traefik]
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.fastbin.entrypoints=websecure"
      - "traefik.http.routers.fastbin.rule=HOST(`$VIRTUAL_HOST`)"
      - "traefik.http.routers.fastbin.service=fastbin-srv"
      - "traefik.http.services.fastbin-srv.loadbalancer.server.port=3000"
      - "traefik.http.services.fastbin-srv.loadbalancer.server.scheme=http"
      - "backup.enable=true"
      - "backup.password=$RESTIC_PASSWORD"
      - "backup.volumes=./data/"


networks:
  traefik:
    external: true
