services:
  synapse:
    image: matrixdotorg/synapse:v1.107.0
    restart: unless-stopped
    networks: [traefik]
    volumes:
      - "${CONTAINER_DIR}/synapse:/data"
    environment:
      - UID=1000
      - GID=1000
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.synapse.entrypoints=websecure"
      - "traefik.http.routers.synapse.rule=HOST(`$VIRTUAL_HOST`)"
      - "traefik.http.routers.synapse.service=synapse-srv"
      - "traefik.http.services.synapse-srv.loadbalancer.server.port=8008"

      - "backup.enable=true"
      - "backup.password=$RESTIC_PASSWORD"
      - "backup.volumes=${CONTAINER_DIR}/synapse"

      - "diun.enable=true"

      - "telegraf.enabled=true"

    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"

networks:
  traefik:
    external: true
