services:

  redis:
    image: redis:7-alpine
    # This is required to stay in RAM only.
    command: redis-server --save "" --appendonly no
    restart: unless-stopped
    tmpfs:
      - /data
    logging:
      driver: none

  app:
    image: cupcakearmy/cryptgeon:latest
    networks: [default,traefik]
    depends_on: [redis]
    restart: unless-stopped
    environment:
      # Size limit for a single note.
      SIZE_LIMIT: 4 MiB
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://127.0.0.1:8000/api/live/"]
      interval: 1m
      timeout: 3s
      retries: 2
      start_period: 5s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.privatebin.entrypoints=websecure"
      - "traefik.http.routers.privatebin.rule=HOST(`$VIRTUAL_HOST`)"
      - "traefik.http.routers.privatebin.service=privatebin-srv"
      - "traefik.http.services.privatebin-srv.loadbalancer.server.port=8000"
      - "traefik.http.services.privatebin-srv.loadbalancer.server.scheme=http"
    logging:
      driver: none

networks:
  traefik:
    external: true

