version: "3.8"

services:
  nextcloud:
    image: nextcloud
    restart: unless-stopped
    networks: [default, traefik]
    depends_on: [redis, db]
    volumes:
      - ${CONTAINER_DIR}/nextcloud:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      - "traefik.http.routers.nextcloud.rule=Host(`$VIRTUAL_HOST`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud,nextcloud_redirect"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

      - "traefik.http.middlewares.nextcloud.headers.stsSeconds=155520011"
      - "traefik.http.middlewares.nextcloud.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.nextcloud.headers.stsPreload=true"
      - "traefik.http.middlewares.nextcloud_redirect.redirectregex.regex=/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud_redirect.redirectregex.replacement=/remote.php/dav/"
    environment:
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=$REDIS_HOST_PASSWORD

      - NEXTCLOUD_TRUSTED_DOMAINS=$VIRTUAL_HOST
      - TRUSTED_PROXIES=$TRUSTED_PROXIES
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW --innodb_read_only_compressed=OF
    restart: unless-stopped
    volumes:
      - "${CONTAINER_DIR}/db:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_DB
      - MYSQL_USER=$DB_USER
      - MYSQL_INITDB_SKIP_TZINFO=1
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"

  redis:
    image: redis:latest
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_HOST_PASSWORD
    restart: unless-stopped
    environment:
      - REDIS_HOST_PASSWORD=$REDIS_HOST_PASSWORD
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"

  nextcloud-cron:
    image: nextcloud
    entrypoint: /cron.sh
    restart: unless-stopped
    depends_on: [db, redis]
    volumes:
      - ${CONTAINER_DIR}/nextcloud:/var/www/html
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"

  backup:
    image: tiredofit/db-backup
    restart: unless-stopped
    depends_on: [db]
    volumes:
      - ${CONTAINER_DIR}/db-backup:/backup
    environment:
      - TIMEZONE=UTC
      - DB_TYPE=mariadb
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=$DB_ROOT_PASSWORD
      - DB_NAME=$DB_DB
      - COMPRESSION=NONE
      - ENABLE_CHECKSUM=FALSE
      - CHECKSUM=SHA1
      - DB_DUMP_BEGIN=0315
      - DB_DUMP_FREQ=1440
      - DB_CLEANUP_TIME=10080
      - CREATE_LATEST_SYMLINK=TRUE
    labels:
      - "backup.enable=true"
      - "backup.password=$RESTIC_PASSWORD"
      - "backup.volumes=${CONTAINER_DIR}/db-backup"
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"

networks:
  traefik:
    external: true
