version: "3"

services:
  web:
    image: nginx:alpine
    volumes:
      - ./data/etc/nginx/:/etc/nginx/conf.d/
      - ./data/web:/var/www/html
    restart: unless-stopped
    depends_on:
      - php
      - db
    networks: [traefik, lnmp]
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.lnmp.entrypoints=websecure"
      - "traefik.http.routers.lnmp.rule=HOST(`$VIRTUAL_HOST`) || HOST(`www.$VIRTUAL_HOST`) || HOST(`$VIRTUAL_HOST2`)"
      - "backup.enable=true"
      - "backup.password=$RESTIC_PASSWORD"
      - "backup.volumes=./data/etc/nginx,./data/web"
      - "backup.exclude=*/downloads/*,*/pma/*,*/ts3wi/*"

  php:
    image: chialab/php:8.1-fpm
    restart: unless-stopped
    networks: [lnmp]
    volumes:
      - ./data/web:/var/www/html

  php7:
    image: chialab/php:7.4-fpm
    restart: unless-stopped
    networks: [lnmp]
    volumes:
      - ./data/web:/var/www/html

  db:
    image: mariadb:10.9
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: default
    volumes:
      - ./data/db:/var/lib/mysql
    networks: [lnmp]

  backup:
    image: tiredofit/db-backup
    depends_on:
      - db
    volumes:
      - ./data/db-backup:/backup
    environment:
      - TIMEZONE=UTC
      - DB_TYPE=mariadb
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=$DB_ROOT_PASSWORD
      - DB_NAME=ALL
      - COMPRESSION=NONE
      - ENABLE_CHECKSUM=FALSE
      - CHECKSUM=SHA1
      - DB_DUMP_BEGIN=0315
      - DB_DUMP_FREQ=1440
      - DB_CLEANUP_TIME=10080
      - CREATE_LATEST_SYMLINK=TRUE
    restart: unless-stopped
    networks: [lnmp]
    labels:
      - "backup.enable=true"
      - "backup.password=$RESTIC_PASSWORD"
      - "backup.volumes=./data/db-backup"

networks:
  lnmp:
  traefik:
    external: true
