version: "3.8"

services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    networks: [default, traefik]
    depends_on:
      - php
      - db
    volumes:
      - ${CONTAINER_DIR}/etc/nginx/:/etc/nginx/conf.d/
      - ${CONTAINER_DIR}/web:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.lnmp.entrypoints=websecure"
      - "traefik.http.routers.lnmp.rule=HOST(`$VIRTUAL_HOST`) || HOST(`www.$VIRTUAL_HOST`) || HOST(`$VIRTUAL_HOST2`)"
      - "backup.enable=true"
      - "backup.password=$RESTIC_PASSWORD"
      - "backup.volumes=${CONTAINER_DIR}/etc/nginx,${CONTAINER_DIR}/web"
      - "backup.exclude=*/downloads/*,*/pma/*,*/ts3wi/*"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  php:
    image: chialab/php:8.1-fpm
    restart: unless-stopped
    volumes:
      - ${CONTAINER_DIR}/web:/var/www/html
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"

  php7:
    image: chialab/php:7.4-fpm
    restart: unless-stopped
    volumes:
      - ${CONTAINER_DIR}/web:/var/www/html
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"

  db:
    image: mariadb:10.9
    restart: unless-stopped
    volumes:
      - ${CONTAINER_DIR}/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: default
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"

  backup:
    image: tiredofit/db-backup
    restart: unless-stopped
    depends_on: [db]
    volumes:
      - ${CONTAINER_DIR}/db-backup:/backup
    environment:
      - TIMEZONE=UTC
      - DB_TYPE=mariadb
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=$DB_ROOT_PASSWORD
      - DB_NAME=ALL
      - COMPRESSION=NONE
      - ENABLE_CHECKSUM=FALSE
      - CHECKSUM=SHA1
      - DB_DUMP_BEGIN=0315
      - DB_DUMP_FREQ=1440
      - DB_CLEANUP_TIME=10080
      - CREATE_LATEST_SYMLINK=TRUE
    labels:
      - "backup.enable=true"
      - "backup.password=$RESTIC_PASSWORD"
      - "backup.volumes=${CONTAINER_DIR}/db-backup"
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"

networks:
  lnmp:
    external: true
