services:
  watchtower:
    image: containrrr/watchtower
    restart: always
    networks: [traefik]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_POLL_INTERVAL=7200
      - WATCHTOWER_NOTIFICATION_URL=$WATCHTOWER_NOTIFICATION_URL
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

# fixes a lot of networking issues
networks:
  traefik:
    external: true
