services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${RELEASE_VERSION}
    restart: unless-stopped
    extends:
      file: hwaccel.transcoding.yml
      service: $HWACCEL
    networks: [default, traefik]
    depends_on:
      - redis
      - database
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.immich.entrypoints=websecure"
      - "traefik.http.routers.immich.rule=HOST(`$IMMICH_DOMAIN`)"
      - "traefik.http.routers.immich.service=immich-srv"
      - "traefik.http.services.immich-srv.loadbalancer.server.port=3001"

      - "backup.enable=true"
      - "backup.password=$RESTIC_PASSWORD"
      - "backup.volumes=${UPLOAD_LOCATION}"

      - "diun.enable=true"

      - "telegraf.enabled=true"

    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${RELEASE_VERSION}
    restart: unless-stopped
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${CONTAINER_DIR}/model-cache:/cache
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    restart: unless-stopped
    volumes:
      - ${CONTAINER_DIR}/pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"

  backup:
    image: tiredofit/db-backup:4.0.19
    restart: unless-stopped
    depends_on: [database]
    volumes:
      - "${CONTAINER_DIR}/db-backup:/backup"
    environment:
      - TIMEZONE=UTC
      - CONTAINER_ENABLE_MONITORING=FALSE
      - DEFAULT_LOG_LEVEL=WARN

      - DEFAULT_CREATE_LATEST_SYMLINK=TRUE
      - BACKUP_JOB_CONCURRENCY=1
      - DEFAULT_CHECKSUM=NONE
      - DEFAULT_COMPRESSION=NONE
      - DEFAULT_BACKUP_INTERVAL=1440
      - DEFAULT_BACKUP_BEGIN=0315
      - DEFAULT_CLEANUP_TIME=10080

      - DB01_TYPE=pgsql
      - DB01_HOST=database
      - DB01_NAME=${DB_DATABASE_NAME}
      - DB01_USER=${DB_USERNAME}
      - DB01_PASS=${DB_PASSWORD}
    labels:
      - "backup.enable=true"
      - "backup.password=$RESTIC_PASSWORD"
      - "backup.volumes=${CONTAINER_DIR}/db-backup"
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"


networks:
  traefik:
    external: true
