version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${RELEASE_VERSION}
    command: ["start-server.sh"]
    restart: unless-stopped
    networks: [default, traefik]
    depends_on:
      - redis
      - database
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.immich.entrypoints=websecure"
      - "traefik.http.routers.immich.rule=HOST(`$IMMICH_DOMAIN`)"
      - "traefik.http.routers.immich.service=immich-srv"
      - "traefik.http.services.immich-srv.loadbalancer.server.port=3001"
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${RELEASE_VERSION}
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    command: ["start-microservices.sh"]
    restart: unless-stopped
    extends:
      file: hwaccel.transcoding.yml
      service: $HWACCEL
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${RELEASE_VERSION}
    restart: unless-stopped
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${CONTAINER_DIR}/model-cache:/cache
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"

  database:
    container_name: immich_postgres
    #image: tensorchord/pgvecto-rs:pg14-v0.1.11
    #image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    restart: unless-stopped
    volumes:
      - ${CONTAINER_DIR}/pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"

networks:
  traefik:
    external: true
