services:
  shoutrrrapi:
    container_name: shoutrrr-api
    image: ghcr.io/gurkengewuerz/shoutrrr-api:develop
    restart: unless-stopped
    networks: [traefik]
    volumes:
      - "${CONTAINER_DIR}/config.yml:/app/config.yml:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.shoutrrr.entrypoints=websecure"
      - "traefik.http.routers.shoutrrr.rule=HOST(`$VIRTUAL_HOST`)"
      - "traefik.http.routers.shoutrrr.service=shoutrrr-srv"
      - "traefik.http.services.shoutrrr-srv.loadbalancer.server.port=3000"
      #- "com.centurylinklabs.watchtower.enable=true"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  traefik:
    external: true
