version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    restart: unless-stopped
    environment:
      - TZ=$TZ
    ports:
      - "1880:1880"
      - "3009:3001"
    volumes:
      - ${CONTAINER_DIR}:/data
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
