version: "3.8"

services:
  node-red:
    image: nodered/node-red:latest
    restart: unless-stopped
    ports:
      - "1880:1880"
      - "3009:3001"
    volumes:
      - ${CONTAINER_DIR}:/data
    environment:
      - TZ=$TZ
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"
