services:
  headscale:
    container_name: "headscale"
    image: ghcr.io/juanfont/headscale:0.27.0
    command: serve
    restart: unless-stopped
    networks: [traefik]
    ports:
      - "3478:3478/udp"
    environment:
      - TZ=$TZ
    volumes:
      - ${CONTAINER_DIR}/headscale/config:/etc/headscale
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.headscale.entrypoints=websecure"
      - "traefik.http.routers.headscale.rule=Host(`$VIRTUAL_HOST`)"
      - "traefik.http.routers.headscale.service=headscale-srv"
      - "traefik.http.services.headscale-srv.loadbalancer.server.port=8080"
      
      - "diun.enable=true"

      - "telegraf.enabled=true"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  headplane:
    container_name: headplane
    image: ghcr.io/tale/headplane:latest
    restart: unless-stopped
    networks: [traefik]
    volumes:
      - "${CONTAINER_DIR}/headplane/config/config.yaml:/etc/headplane/config.yaml"
      # This should match headscale.config_path in your config.yaml
      - "${CONTAINER_DIR}/headscale/config:/etc/headscale"
      # Headplane stores its data in this directory
      - "${CONTAINER_DIR}/headplane/data:/var/lib/headplane"

      # If you are using the Docker integration, mount the Docker socket
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.headscale-web.entrypoints=websecure"
      - "traefik.http.routers.headscale-web.rule=HOST(`$VIRTUAL_HOST`) && PathPrefix(`/admin`)"
      - "traefik.http.routers.headscale-web.service=headscale-web-srv"
      - "traefik.http.services.headscale-web-srv.loadbalancer.server.port=3000"
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"

networks:
  traefik:
    external: true
