version: "3.8"

services:
  # API Key:
  # docker compose exec headscale headscale apikeys create --expiration 90d
  headscale:
    image: headscale/headscale:0.22
    command: headscale serve
    restart: unless-stopped
    networks: [traefik]
    ports:
      - "3478:3478/udp"
    volumes:
      - ${CONTAINER_DIR}/headscale/config:/etc/headscale
      - ${CONTAINER_DIR}/headscale/data:/var/lib/headscale
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.headscale.entrypoints=websecure"
      - "traefik.http.routers.headscale.rule=(Host(`$VIRTUAL_HOST`) || Host(`$VIRTUAL_HOST_ALT`))"
      - "traefik.http.routers.headscale.service=headscale-srv"
      - "traefik.http.services.headscale-srv.loadbalancer.server.port=8080"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  headscale-webui:
    image: ghcr.io/ifargle/headscale-webui:latest
    restart: unless-stopped
    networks: [traefik]
    volumes:
      - ${CONTAINER_DIR}/headscale-web/:/data
      - ${CONTAINER_DIR}/headscale/config/:/etc/headscale/:ro
    environment:
      - TZ=$TZ
      - COLOR=purple
      - HS_SERVER=http://headscale:8080
      - DOMAIN_NAME=https://$VIRTUAL_HOST
      - SCRIPT_NAME=/web
      - KEY=$UI_SECRET_KEY
      - AUTH_TYPE=
      - LOG_LEVEL=info
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.headscale-web.entrypoints=websecure"
      - "traefik.http.routers.headscale-web.rule=(HOST(`$VIRTUAL_HOST`) || HOST(`$VIRTUAL_HOST_ALT`)) && PathPrefix(`/web`)"
      - "traefik.http.routers.headscale-web.service=headscale-web-srv"
      - "traefik.http.services.headscale-web-srv.loadbalancer.server.port=5000"
      - "traefik.http.routers.headscale-web.middlewares=headscale-web-auth"
      - "traefik.http.middlewares.headscale-web-auth.basicauth.users=$UI_USER:$UI_PASSWORD"
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"

networks:
  traefik:
    external: true
