version: "3.8"

services:
  ipv6nat:
    container_name: ipv6nat
    image: robbertkl/ipv6nat
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/lib/modules:/lib/modules:ro"
