services: 
  virt-manager:
    image: mber5/virt-manager:latest
    restart: unless-stopped
    privileged: true
    networks: [traefik]
    environment:
      DARK_MODE: true
      HOSTS: "['qemu:///system']"
    volumes:
      - "/var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock"
      - "/var/lib/libvirt/images:/var/lib/libvirt/images"
    devices:
      - "/dev/kvm:/dev/kvm"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.kvm.entrypoints=web"
      - "traefik.http.routers.kvm.rule=Host(`${VIRTUAL_HOST}`)"
      - "traefik.http.routers.kvm.priority=100"
      - "traefik.http.services.kvm.loadbalancer.server.port=80"

networks:
  traefik:
    external: true

