version: '3'

services:
  mongo:
    image: mongo:3.6
    restart: unless-stopped
    ports:
      - "3999:27017/tcp"
    volumes:
      - /root/unifi/data/mongo/db:/data/db
      - /root/unifi/data/mongo/config:/data/configdb
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

  controller:
    image: "jacobalberty/unifi:latest"
    depends_on:
      - mongo
    init: true
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - /root/unifi/data/unifi:/unifi
      - init:/unifi/init.d
      - run:/var/run/unifi
    environment:
      DB_URI: mongodb://$HOST_IP:3999/unifi
      STATDB_URI: mongodb://$HOST_IP:3999/unifi_stat
      DB_NAME: unifi
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
    #ports:
    #  - "3478:3478/udp" # STUN
    #  - "6789:6789/tcp" # Speed test
    #  - "8080:8080/tcp" # Device/ controller comm.
    #  - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
    #  - "8880:8880/tcp" # HTTP portal redirection
    #  - "8843:8843/tcp" # HTTPS portal redirection
    #  - "10001:10001/udp" # AP discovery

volumes:
  init:
  run:
