version: "3.8"

services:
  controller:
    image: "jacobalberty/unifi:latest"
    init: true
    network_mode: "host"
    restart: unless-stopped
    depends_on: [mongo]
    volumes:
      - ${CONTAINER_DIR}/unifi:/unifi
      - init:/unifi/init.d
      - run:/var/run/unifi
    environment:
      DB_URI: mongodb://$HOST_IP:3999/unifi
      STATDB_URI: mongodb://$HOST_IP:3999/unifi_stat
      DB_NAME: unifi
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    #ports:
    #  - "3478:3478/udp" # STUN
    #  - "6789:6789/tcp" # Speed test
    #  - "8080:8080/tcp" # Device/ controller comm.
    #  - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
    #  - "8880:8880/tcp" # HTTP portal redirection
    #  - "8843:8843/tcp" # HTTPS portal redirection
    #  - "10001:10001/udp" # AP discovery

  mongo:
    image: mongo:3.6
    restart: unless-stopped
    ports:
      - "3999:27017/tcp"
    volumes:
      - ${CONTAINER_DIR}/mongo/db:/data/db
      - ${CONTAINER_DIR}/mongo/config:/data/configdb
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"

volumes:
  init:
  run:
