version: "3.8"

services:
  ddns-updater:
    image: qmcgaw/ddns-updater
    restart: always
    ports:
      - 8000:8000/tcp
    volumes:
      - ${CONTAINER_DIR}/ddns:/updater/data
    environment:
      - PERIOD=5m
      - UPDATE_COOLDOWN_PERIOD=5m
      - PUBLICIP_FETCHERS=dns
      - PUBLICIP_DNS_PROVIDERS=all
      - PUBLICIP_DNS_TIMEOUT=5s

      # Web UI
      - LISTENING_PORT=8000
      - ROOT_URL=/
      - SHOUTRRR_ADDRESSES=$SHOUTRRR_ADDRESSES
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"
