version: "3.7"

services:

  ddns-updater:
    image: qmcgaw/ddns-updater
    ports:
      - 8000:8000/tcp
    volumes:
      - ./data/ddns:/updater/data
    environment:
      - PERIOD=5m
      - UPDATE_COOLDOWN_PERIOD=5m
      - PUBLICIP_FETCHERS=dns
      - PUBLICIP_DNS_PROVIDERS=all
      - PUBLICIP_DNS_TIMEOUT=5s
      
      # Web UI
      - LISTENING_PORT=8000
      - ROOT_URL=/
      - SHOUTRRR_ADDRESSES=$SHOUTRRR_ADDRESSES
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

