version: "3.8"

services:
  ddns-updater:
    image: qmcgaw/ddns-updater
    restart: always
    networks: [traefik]
    volumes:
      - ${CONTAINER_DIR}/ddns:/updater/data
    environment:
      - PERIOD=5m
      - UPDATE_COOLDOWN_PERIOD=5m
      - PUBLICIP_FETCHERS=dns
      - PUBLICIP_DNS_PROVIDERS=all
      - PUBLICIP_DNS_TIMEOUT=5s

      # Web UI
      - LISTENING_PORT=8000
      - ROOT_URL=/
      - SHOUTRRR_ADDRESSES=$SHOUTRRR_ADDRESSES
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.ddns.entrypoints=web"
      - "traefik.http.routers.ddns.rule=Host(`${VIRTUAL_HOST}`)"
      - "traefik.http.routers.ddns.priority=100"
      - "traefik.http.services.ddns.loadbalancer.server.port=8000"

    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"

networks:
  traefik:
    external: true

