version: "3.8"

services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    restart: unless-stopped
    networks: [traefik]
    volumes:
      - "${CONTAINER_DIR}/coder/config:/config"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
      - PASSWORD=$PASSWORD
      - SUDO_PASSWORD=$SUDO_PASSWORD
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.coder.entrypoints=websecure"
      - "traefik.http.routers.coder.rule=HOST(`$VIRTUAL_HOST`)"
      - "traefik.http.routers.coder.service=coder-srv"
      - "traefik.http.services.coder-srv.loadbalancer.server.port=8443"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  traefik:
    external: true
